########################################
# General
########################################

threads: 8

reads: "reads"
results: "results"

########################################
# Subsampling
########################################

genome_sizes:
  abaumannii: 4000000
  paeruginosa: 6700000
  kpneumoniae: 5500000

target_coverage: 120

########################################
# BUSCO
########################################

busco:
  threads: 8

busco_lineages:
  abaumannii: pseudomonadales_odb10
  paeruginosa: pseudomonadales_odb10
  kpneumoniae: pseudomonadales_odb10

########################################
# Bakta
########################################

bakta:
  db: /Users/louis/databases/bakta/db-light
  threads: 8

########################################
# MLST
########################################

mlst:
  threads: 8

########################################
# AMRFinderPlus
########################################

amrfinder:
  threads: 8
  database: "/Users/louis/databases/amrfinder/latest"

amrfinder_organisms:
  abaumannii: Acinetobacter_baumannii
  paeruginosa: Pseudomonas_aeruginosa
  kpneumoniae: Klebsiella_pneumoniae
########################################
# VFDB
########################################
vfdb:
  db: /Users/louis/Downloads/Acinetobacter_WGS_Snakemake/databases/vfdb/VFDB_prot
  threads: 8
########################################
# MOB-suite
########################################

mobsuite:
  threads: 8

########################################
# FastANI
########################################

fastani:
  threads: 8

########################################
# Species groups
########################################

species_groups:
  abaumannii:
    - AB68
    - AB70
    - AB71

  paeruginosa:
    - AB69

########################################
# Panaroo
########################################

panaroo:
  threads: 8

########################################
# IQ-TREE
########################################

iqtree:
  threads: 8