########################################
# General
########################################

threads: 8
memory_mb: 7000

reads: "reads"
results: "results"

########################################
# Subsampling
########################################

genome_sizes:
  abaumannii: 4000000
  paeruginosa: 6700000
  kpneumoniae: 5500000

default_genome_size: 7000000

target_coverage: 120

########################################
# BUSCO
########################################

busco:
  threads: 8

busco_lineages:
  Acinetobacter: pseudomonadales_odb10
  Klebsiella: enterobacterales_odb10

########################################
# Bakta
########################################

bakta:
  db: /home/louis/databases/bakta/db-light
  threads: 8

########################################
# Prokka
########################################

prokka:
  threads: 8

########################################
# MLST
########################################

mlst:
  threads: 8

########################################
# AMRFinderPlus
########################################

amrfinder:
  threads: 8
  database: "/home/louis/databases/amrfinder/latest"

amrfinder_organisms:
  Acinetobacter: Acinetobacter_baumannii
  Klebsiella: Klebsiella_pneumoniae

amrfinder_sample_overrides:
  AB69: Pseudomonas_aeruginosa
########################################
# VFDB
########################################
vfdb:
  db: /home/louis/databases/vfdb/VFDB_prot
  threads: 8
  min_identity: 80
  min_coverage: 80
########################################
# MOB-suite
########################################

mobsuite:
  threads: 8

########################################
# FastANI
########################################

fastani:
  threads: 8

########################################
# Species groups
########################################

species_groups:
  abaumannii:
    - AB68
    - AB70
    - AB71

  paeruginosa:
    - AB69

########################################
# Panaroo
########################################

panaroo:
  threads: 8

########################################
# IQ-TREE
########################################

iqtree:
  threads: 8
